version: "3"

services:
  postgres:
    image: "postgres:latest"
    command: ["postgres", "-c", "log_connections=on"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pg_local_password
      POSTGRES_USER: local_user
      POSTGRES_DB: local_db
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4597:4566-4597"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53,sqs,sns,ssm
      - LAMBDA_DOCKER_NETWORK=localstack-external
      - LAMBDA_EXECUTOR=local
      - PORT_WEB_UI=8080
      - DEBUG=1
    volumes:
      - ./docker/localstack:/docker-entrypoint-initaws.d
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  default:
    name: localstack-external
